# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - health-bot-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies with Poetry
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest
        env:
          PYTHONPATH: .

      - name: Prepare artifact for deployment
        run: |
          mkdir -p artifact/app
          if [ ! -d app ]; then echo "ERROR: 'app' directory does not exist!"; exit 1; fi
          cp -a app/. artifact/app/
          cp pyproject.toml poetry.lock startup.sh artifact/
      - name: List files in artifact (debug)
        run: |
          echo "Listing artifact contents after build:"
          ls -R artifact

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: artifact/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A7BEA195273F4B8A949D99C3B93ECAA2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF2B7D6206EA4FC0B89EC79E55333572 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28D24910D62A469484B8E6195F7262D5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'health-bot-api'
          slot-name: 'Production'
          
